### ISSUE TITLE
npm not added to path

### ISSUE THREAD

**Issue by chelming** [MattHodge/PoshHubot#1]
For whatever reason, `Install-Hubot` isn't adding npm to `$env:path` and then fails trying to run yo. Chocolaty got added but not npm. Server 2012 R2, Powershell 4.0.

**Comment by MattHodge** [comment]
Hi @cwhits.

Try running this:

``` powershell
([System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")) -split ';'
```

Do you see `C:\Program Files\nodejs\` in that list?

**Comment by chelming** [comment]
Yep.

Yo is installing to my appdata folder though... `C:\Users\cwhits\AppData\Roaming\npm`

**Comment by MattHodge** [comment]
This should be resolved now.
