### ISSUE TITLE
Add ability to run Hubot as specific user other than SYSTEM

### ISSUE THREAD

**Issue by chelming** [MattHodge/PoshHubot#3]
Is there a way to run hubot not as SYSTEM but as a specific user?

**Comment by chelming** [comment]
I couldn't get it to run as a specific user by adding `-runas` to the `start-process` command, but only by using `runas` before the argument list. `ArgumentList = "runas /user:cwhits cmd.exe /c forever star...`

**Comment by MattHodge** [comment]
@cwhits, what is your use case so I can target my testing to it. 

Is your plan to have the Hubot running under a domain service account so it can authenticate with PowerShell without having to use credentials?

I will investigate

**Comment by chelming** [comment]
Exactly. I'd run hubot as a service account so I can avoid having creds stored in scripts.

Ideally I'd be putting the scripts/commands in git and allowing other teammates or service desk operators to contribute commands, but wouldn't necessarily want them to know the credentials for the service account.

**Comment by MattHodge** [comment]
I created a DSC Resource which can do this for you: https://github.com/MattHodge/Hubot-DSC-Resource
