### ISSUE TITLE
Auto-start after reboot

### ISSUE THREAD

**Issue by chelming** [MattHodge/PoshHubot#4]
Do you have anything in place to auto-start hubot after a reboot? Startup script?

**Comment by MattHodge** [comment]
Hi @cwhits.. I am in the final stages of finishing a DSC resource that installs Hubot.

I am using NSSM to start the service - you can take a look here: https://github.com/MattHodge/Hubot-DSC-Resource

**Comment by MattHodge** [comment]
I created a DSC resource which can do this for you: https://github.com/MattHodge/Hubot-DSC-Resource
